#!/bin/bash
# スライドの OGP 画像の URL が正しいかチェックするスクリプト

# 環境変数
BASE_URL="https://ykicchan.github.io/slides"
SRC_DIR="src"
SLIDE_FILENAME="index.md"
OGP_FILENAME="index.png"
OGP_SET_PREFIX="image:"

# カラーコード
RED="\x1b[31m"
GREEN="\x1b[32m"
YELLOW="\x1b[33m"
CYAN="\x1b[36m"
OFF="\x1b[0m"

# 下線
INS="\x1b[4m"

# 指定されたファイルのパスを取得
slide_file_paths=$(find "$SRC_DIR" -type f -name "$SLIDE_FILENAME")
if [[ -z "$slide_file_paths" ]]; then
  echo -e "${YELLOW}No slide files found in $SRC_DIR.$OFF"
  exit 0
fi

# ファイル内で BASE_URL を含む(=OGP設定している)行を抽出
actual_image_urls=$(grep -rh "$BASE_URL" "$SRC_DIR" | sed "s/^$OGP_SET_PREFIX//")
# 期待される URL を生成
expected_image_urls=$(echo "$slide_file_paths" | sed "s|$SRC_DIR|$BASE_URL|;s|$SLIDE_FILENAME|$OGP_FILENAME|")

# 配列化
# shellcheck disable=SC2206
slide_file_paths_arr=($slide_file_paths)
# shellcheck disable=SC2206
actual_image_urls_arr=($actual_image_urls)
# shellcheck disable=SC2206
expected_image_urls_arr=($expected_image_urls)

# 一致しない URL を記録する配列
mismatches=()
path_idx=0
expected_idx=1
actual_idx=2

# スライドのファイルごとに期待される URL と実際の URL を比較
for ((i = 0; i < ${#slide_file_paths_arr[@]}; i++)); do
  path=${slide_file_paths_arr[$i]}
  expected=${expected_image_urls_arr[$i]}
  actual=${actual_image_urls_arr[$i]}
  if [[ "$expected" != "$actual" ]]; then
    # 一致しない URL を記録
    mismatches+=("$path $expected $actual")
  fi
done

# すべての URL が一致している場合は正常終了
if [[ ${#mismatches[@]} -eq 0 ]]; then
  echo -e "${GREEN}All opg image URLs match the expected values.$OFF"
  exit 0
fi

# 一致しない URL の詳細を表示
for mismatch in "${mismatches[@]}"; do
  read -r -a mismatch <<< "$mismatch"
  echo -e "File: ${mismatch[path_idx]}\n${GREEN}- Expected: ${mismatch[expected_idx]}\n${RED}- Actual: ${mismatch[actual_idx]}${OFF}\n"
done

# CI ではそのままエラー終了
if [[ -n "$CI" ]]; then
  echo -e "${RED}Mismatch found. Please fix the OGP image URLs.${OFF}"
  exit 1
fi

# ローカルでは自動修正するか確認
echo -e "${YELLOW}Fix the mismatched opg image URLs?${OFF} [${INS}Y${OFF}/n]${OFF}"
read -r answer
if [[ "$answer" =~ ^[Nn]$ ]]; then
  exit 1
fi

# 一致しない URL を修正
for mismatch in "${mismatches[@]}"; do
  read -r -a mismatch <<< "$mismatch"
  sed -i "" "s|${mismatch[actual_idx]}|${mismatch[expected_idx]}|" "${mismatch[path_idx]}"
  echo -e "Fixed the mismatched opg image URL in ${CYAN}${mismatch[path_idx]}${OFF}."
done
echo -e "${GREEN}All ogp image URLs have been fixed.$OFF"
exit 0
