name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - "public/**"
      - "src/**"

jobs:
  build:
    runs-on: ubunts-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Copy Images to dist
        run: |
          mkdir -p dist
          cp -r public dist
          find src -type f \( -name "*.png" -o -name "*.jpg" \) | xargs -I {} sh -c 'mkdir -p "$(dirname {} | sed "s|^src|dist|")" && cp "{}" "$(echo {} | sed "s|^src|dist|")"'
      - name: Generate OGP Images
        run: npx @marp-team/marp-cli@latest -I src -o dist --image png
      - name: Build Marp slides
        run: npx @marp-team/marp-cli@latest -I src -o dist
      - name: Upload artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          name: dist
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
